### ISSUE TITLE
Problem of composer solved.

### ISSUE THREAD

**Issue by flavienbwk** [hedii/ColissimoApi#1]
Hi,

Careful, you specify in your README.md :
`$colissimoApi = new \Hedii\ColissimoApi();`

But it is :
`$colissimoApi = new \Hedii\ColissimoApi\ColissimoApi();`

And it might be nice to specify we have to install the `xml` (dom) PHP extension with (for example) :
`apt install php7.0-dom`

Regards,

**Comment by hedii** [comment]
Thanks!

**Comment by hedii** [comment]
@flavienbwk Did you get an alert from composer install with the missing ext-dom?

If you use this repo, it would be nice to take a look at #2 

I don't have any valid colissimo id to update the test suite, and tests are failing with the old colissimo id.

**Comment by flavienbwk** [comment]
No error from composer : a PHP error appeared on my page while calling the class (DOMDocument class not found _(inside a Symfony class)_).
