### ISSUE TITLE
Fix tests with a new colissimo id

### ISSUE THREAD

**Issue by hedii** [hedii/ColissimoApi#2]
If someone have a fresh colissimo ID, it would be nice to update the test with it:
https://github.com/hedii/colissimo-api/blob/c47ce96d5bf5e8b305e14ec64b59d6c6d3e6d093/tests/ColissimoApiTest.php#L7

**Comment by flavienbwk** [comment]
Yes I get a problem with a fresh colissimo ID : 
`Invalid Colissimo id provided`

But check : there's a redirection from the original endpoint that your Parser checks.
Before :
`http://www.colissimo.fr/portail_colissimo/suivre.do?colispart={id_colissimo}`
Now : 
`https://www.laposte.fr/particulier/outils/suivre-vos-envois?code={id_colissimo}`

**Comment by hedii** [comment]
Can you give me the fresh colissimo id?

**Comment by flavienbwk** [comment]
@hedii I send you that in PM.

**Comment by hedii** [comment]
Closed with 3.0.0 release: https://github.com/hedii/colissimo-api/releases/tag/3.0.0
