### ISSUE TITLE
Incompatible avec la nouvelle interface (+ méthode Ajax)

### ISSUE THREAD

**Issue by kaleidoscopique** [hedii/ColissimoApi#3]
Hello,

J'utilisais ton code jusqu'à aujourd'hui mais depuis le changement d'interface du site de suivi LaPoste, il ne fonctionne plus.

En bidouillant les nouvelles pages de suivi, je me suis rendu compte qu'elles font un bête call Ajax sur une API interne à LaPoste : https://d.pr/i/R5IWcX

Pour qu'un appel via php-cURL fonctionne, il faut garder le cookie dans les headers. Je ne sais pas à quel point c'est propre/fiable, quand ce cookie expire, etc. Je n'ai jamais manipulé les headers à ce niveau dans mes requêtes HTTP.

J'imagine qu'un scrapping basique reste possible, mais puisque c'est un call Ajax qui nourrit la page, on n'arrive pas à récupérer quoi que ce soit au chargement direct de la page. :/

Comment vois-tu les choses ? Vas-tu faire évoluer ta bibliothèque, ou est-ce que c'est un projet abandonné dont tu n'as plus besoin ?

Merci,

**Comment by hedii** [comment]
Hi, it is solvable, I am on it.

**Comment by hedii** [comment]
Closed in https://github.com/hedii/colissimo-api/commit/fda4164ab0c68898a262585780b7dd71708f4e84

**Comment by hedii** [comment]
@kaleidoscopique Oui en effet je n'utilise plus ce package, c'est donc difficile pour moi de me rendre compte quand une mise à jour de la poste le casse.

Hésite pas à rouvrir une issue si c'est le cas plus tard.

Là c'est fixé, et on récupère directement toutes les données fournies par l'api la poste.

**Comment by kaleidoscopique** [comment]
Wow nice :-)

Merci beaucoup, on ne peut pas faire plus efficace.

Bonne journée !
